spring:
  application:
    name: todo
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    defer-datasource-initialization: true
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true


springdoc:
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true

jwt:
  secret: ${JWT_SECRET:your-very-secure-secret-key-that-is-at-least-32-characters-long}

security:
  admin:
    username: admin
    password: BlueSky


# logging:
#   level:
#     org.springframework.graphql: DEBUG
#     org.springframework.security: DEBUG


# logging.level.org.springframework.security=DEBUG




