# spring:
#   web:
#     resources:
#       static-locations: classpath:/static/
#   mvc:
#     static-path-pattern: "/"



jwt:
  # Set the JWT_SECRET environment variable to a secure value
  secret: ${JWT_SECRET:your-very-secure-secret-key-that-is-at-least-32-characters-long}

# springdoc:
#     swagger-ui:
#         oauth:
#             clientId: swagger
#             realm: realm
#             use-pkce-with-authorization-code-grant: true

springdoc:
  swagger-ui:
    oauth:
      client-id: ""
      client-secret: ""
      use-pkce-with-authorization-code-grant: true






# logging.level.org.springframework.web.filter=DEBUG
# logging.level.org.springframework.web.servlet.HandlerInterceptor=DEBUG


logging:
  level:
    org.springframework.web.filter: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.servlet.HandlerInterceptor: DEBUG

